name: Haskell CI

on:
  push:
    branches: 
      - dev

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: cabal-data        
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-install --only-dependencies --enable-tests
    - name: Build
      run: |
        cabal new-configure --enable-tests
        cabal new-build
        cabal new-exec site clean
        cabal new-exec site build
    - name: Update master
      run: cabal test
